import streamlit as st
from confluent_kafka import Consumer
import json
import pandas as pd
import numpy as np
import os
import time
import plotly.express as px
import plotly.graph_objects as go

bootstrap_servers = os.getenv("KAFKA_BOOTSTRAP_SERVERS")

st.set_page_config(layout="wide")
st.title("Real-Time Flight Delay Monitoring")

st.markdown(
"""
This dashboard displays real-time delay probability predictions 
generated by the streaming ML model.
"""
)

if "data" not in st.session_state:
    st.session_state.data = []

if "consumer" not in st.session_state:
    consumer = Consumer({
        'bootstrap.servers': bootstrap_servers,
        'group.id': 'dashboard_group',
        'auto.offset.reset': 'earliest',
        'enable.auto.commit': True
    })
    consumer.subscribe(["predictions"])
    st.session_state.consumer = consumer

consumer = st.session_state.consumer

st.sidebar.header("Dashboard Settings")

window_size = st.sidebar.slider(
    "Number of recent flights to display",
    50, 1000, 200, 50
)

rolling_window = st.sidebar.slider(
    "Rolling average window size",
    5, 100, 20, 5
)

auto_refresh = st.sidebar.checkbox("Auto refresh", value=True)

for _ in range(20):
    msg = consumer.poll(0.1)
    if msg and not msg.error():
        st.session_state.data.append(
            json.loads(msg.value().decode())
        )

if len(st.session_state.data) == 0:
    st.warning("Waiting for streaming data...")
    st.stop()

df = pd.DataFrame(st.session_state.data[-window_size:])

df["rolling_mean"] = df["probability"].rolling(rolling_window).mean()
df["predicted_delay"] = df["probability"] > 0.5

st.subheader("Current Metrics")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Average Delay Probability",
        f"{df['probability'].mean():.3f}"
    )

with col2:
    st.metric(
        "Predicted Delay Rate",
        f"{df['predicted_delay'].mean():.2%}"
    )

with col3:
    if "true_label" in df.columns:
        accuracy = (df["predicted_delay"] == df["true_label"]).mean()
        st.metric("Model Accuracy", f"{accuracy:.2%}")
    else:
        st.metric("Model Accuracy", "N/A")

st.subheader("Delay Probability Over Time")

fig = go.Figure()

fig.add_trace(go.Scatter(
    y=df["probability"],
    mode='lines',
    name='Raw Probability'
))

fig.add_trace(go.Scatter(
    y=df["rolling_mean"],
    mode='lines',
    name='Rolling Average',
    line=dict(width=4)
))

fig.update_layout(
    xaxis_title="Flight Index (stream order)",
    yaxis_title="Delay Probability",
    legend_title="Legend",
    template="plotly_white"
)

st.plotly_chart(fig, use_container_width=True)

st.caption(
"""
Raw probability shows individual flight predictions.  
Rolling average smooths short-term fluctuations to highlight trends.
"""
)

st.subheader("Probability Distribution")

fig_hist = px.histogram(
    df,
    x="probability",
    nbins=20,
    title="Distribution of Predicted Delay Probabilities"
)

fig_hist.update_layout(
    xaxis_title="Probability",
    yaxis_title="Count",
    template="plotly_white"
)

st.plotly_chart(fig_hist, use_container_width=True)

if "source" in df.columns:
    st.subheader("Average Probability by Source")

    avg_by_source = df.groupby("source")["probability"].mean().reset_index()

    fig_bar = px.bar(
        avg_by_source,
        x="source",
        y="probability",
        title="Average Delay Probability by Data Source"
    )
    fig_bar.update_layout(
        xaxis_title="Source",
        yaxis_title="Average Probability",
        template="plotly_white"
    )
    st.plotly_chart(fig_bar, use_container_width=True)
if auto_refresh:
    time.sleep(1)
    st.rerun()